version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
