services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
      - redis

  db:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "zemi_counter"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: "redis:alpine"

volumes:
  db-data:
